### PR TITLE
SparrowCI pipeline

### PR DESCRIPTION
**Pull request by melezhik**
Hi! This pipeline runs unit tests and executes example code taken from readme page. in case any errors during sample code execution it marks an entire build with warning ... maybe this could be useful beyond existing GH action?

An example build is here - https://ci.sparrowhub.io/report/2373

### CODE REVIEW

**Comment by frithnanth** [comment]
Thank you

**Comment by melezhik** [comment]
Thanks. You need to add this repo to your repositories list in SparrowCI account so that builds start trigger

**Comment by frithnanth** [comment]
Done

**Comment by melezhik** [comment]
Hm.  Don’t see any new builds … Do you see this repo in your account ?

**Comment by frithnanth** [comment]
When I added it it showed in the "Active repos" tab. Now it's gone; moreover when I try to add it again using my GitHub repository URL (https://github.com/frithnanth/raku-Math-Libgsl-Wavelet) it does nothing anymore.

**Comment by melezhik** [comment]
Ok, I will troubleshoot once I get my laptop

**Comment by melezhik** [comment]
Please try to add repo again. It should work now. I have fixed a bug in SparrowCI repository addition action.

**Comment by frithnanth** [comment]
Yes, now it worked

**Pull request merged**
